### ISSUE TITLE
Enemy spawn problems

### ISSUE THREAD

**Issue by Zenfros** [deathlysamurai/EmptiveEscort#16]
Enemies spawn inside of geometry and remain stuck. 
Enemies spawn outside of the blocking volumes and cannot enter the level. 
Sometimes melee enemies stuck behind the blocking volumes continually hit the escort while remaining in place.

**Comment by deathlysamurai** [comment]
I made enemies try 10 times to spawn at random locations before giving up and not spawning.

I am not worrying about the blocking volumes because the future gameplay may not involve this issue, and it would probably make more sense to increase the area of the blocking volumes if needed.
